version: "3"

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  node-red:
    image: nodered/node-red:1.0.0-10-arm32v7
    environment:
      - TZ=Europe/Madrid
    ports:
      - "1880:1880"
    volumes:
      - /home/pi/node-red:/data
    links:
      - mosquitto
      - influxdb
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - /home/pi/mqtt/config:/mosquitto/config
      - /home/pi/mqtt/data:/mosquitto/data
      - /home/pi/mqtt/log:/mosquitto/log
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    volumes:
      - /home/pi/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    volumes:
      - /home/pi/chronograf:/var/lib/chronograf
    links:
      - influxdb

  python3:
    build: python 
    volumes:
      - /home/pi/python:/usr/src/myapp
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
    environment:
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      
  python3_mitemp:
     build: python_mitemp
     stdin_open: true
     tty: true
     privileged: true
     network_mode: "host"

volumes:
  portainer_data:
